Disallowed `NaN` and `Infinity` values in JSONs sent to the Apify API (#87)
If you tried to push an item which contained a `NaN` to a dataset, it
would return an error from the Apify API, that the JSON you sent to it
is invalid.

```python
>>> client.dataset('~nan-testing-dataset').push_items([{ 'a': float('NaN')}])
ApifyApiError: Cannot parse POST payload as JSON: Unexpected token N in JSON at position 7
```

That is because in Python, by default, `json.dumps()` stringifies `NaN`
and `Infinity` values. This is against the JSON standard, and
`JSON.parse` on the API fails to parse the value.

This fixes it by adding the `allow_nan=False` parameter to
`json.dumps()`, so that the error is caught before sending the invalid
JSON to the API, and throws an error early.

```python
>>> client.dataset('~nan-testing-dataset').push_items([{ 'a': float('NaN')}])
ValueError: Out of range float values are not JSON compliant: nan
```